#!/bin/bash
echo "obase=$BESTCHOL_BASE; $(echo "ibase=$WATER_BASE; $WATER" | tr 0-9a-f A-F | xargs -I {} echo "{} + ibase=$STIR_BASE; $STIR" | tr 0-9a-f A-F)" | tr A-F 0-9a-f | xargs -I {} echo "{}" | bc
